apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-7ijf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-sombaner-tenant/partner-catalog/partner-catalog-7ijf@sha256:a603ebd9d2c015db693e6c3920c23fc41129091f01e6f2a2c2fcfb1ecb1b95b8
        name: my-java-springboot
        resources: {}
status: {}
