apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-7ijf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-sombaner-tenant/partner-catalog/partner-catalog-7ijf@sha256:dc08c9a358e86e1d0947fede454973e1cbcf4dc5768af68e84500010cc104aff
        name: my-java-springboot
        resources: {}
status: {}
