apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-7ijf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-sombaner-tenant/partner-catalog/partner-catalog-7ijf@sha256:4eab4afa18d17893b597b0c8f0b84e0cdb3a2fda5a85828ef4a56c3b8f963df8
        name: my-java-springboot
        resources: {}
status: {}
