apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-7ijf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-sombaner-tenant/partner-catalog/partner-catalog-7ijf@sha256:8d0c960ff9190d7e74bd11434243cbdb2894bf5f66acab9cc78feca60b7b95c7
        name: my-java-springboot
        resources: {}
status: {}
